[project]
name = "dash-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.1.1",
    "pandas>=2.3.0",
    "rich>=14.0.0",
    "watchdog>=6.0.0",
]
